[font]
size = 11
normal.family = "JetBrainsMono Nerd Font"

[window]
blur = true
decorations = "none"
opacity = 0.8
padding.x = 10
padding.y = 10
decorations_theme_variant = "dark"
startup_mode = "Maximized"

[selection]
save_to_clipboard = true
