# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# See bash(1) for more options

HISTSIZE=5000 # for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTFILESIZE=8000
HISTCONTROL=ignoreboth:erasedups 
PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND$'\n'}history -a; history -c; history -r" # After each command, append to the history file and reread it

(which nvim &>/dev/null && EDITOR=`which nvim`)  \
    || (which vim &>/dev/null && EDITOR=`which vim`) \
        || (which vi &>/dev/null && EDITOR=`which vi`) \
            || (which nano &>/dev/null && EDITOR=`which nano`)

shopt -s autocd # a directory is executed as if it were the argument to the cd command.
shopt -s checkwinsize # check and update the values of LINES and COLUMNS.
shopt -s globstar # If set, the pattern "**" used in a pathname expansion context will match all files and zero or more directories and subdirectories.
shopt -s histappend # When the shell exits, append to the history file instead of overwriting it
shopt -s cmdhist # If set, bash attempts to save all lines of a multiple-line command in the same history  entry.  This allows easy re-editing of multi-line commands.
 
# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi


# Add default ssh-key to ssh agent
empty -f ssh-add
pass show ssh/id_rsa | head -n1 | empty -s 

function __load_file_if_exists() {
    if [[ -f "$1" ]]; then
        source "$1"
    fi
}

# Load all files under the .config/bash/ directory 
function __load_bash_files_from_dir() {
    for f in $1; do 
        [[ ${f##*/} != "bashrc" ]] && source $f 
    done
}

# Custom bash configuration
__load_bash_files_from_dir "$HOME/.config/bash/*" 


[ -f ~/.fzf.bash ] && source ~/.fzf.bash
